version: 2.1
orbs:
  node: circleci/node@4.9.0
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '16.13.1'
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm run build:cjs
      - run: npm test
      - persist_to_workspace:
          root: ~/project
          paths:
            - codemirror/dist
            - kvsearch/dist
  benchmark:
    executor:
      name: node/default
      tag: '16.13.1'
    steps:
      - checkout
      - node/install-packages
      - run: cd kvsearch && npm run benchmark
  lint-lib:
    executor:
      name: node/default
      tag: '16.13.1'
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint
  publish-kvsearch:
    executor:
      name: node/default
      tag: '16.13.1'
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/project/kvsearch/.npmrc
      - run: cd kvsearch && npm publish ./ --access public
workflows:
  version: 2
  test-deploy:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
      - benchmark:
          filters:
            tags:
              ignore: /.*/
      - lint-lib:
          filters:
            tags:
              ignore: /.*/
      - publish-kvsearch:
          requires:
            - build-and-test
          filters:
            tags:
              only: /kvsearch-.*/
            branches:
              ignore: /.*/
