version: 2.1
orbs:
  node: circleci/node@4.9.0
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '16.13.1'
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm test
  lint-lib:
    executor:
      name: node/default
      tag: '16.13.1'
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint

workflows:
  version: 2
  test-deploy:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
      - lint-lib:
          filters:
            tags:
              ignore: /.*/
