name: ci
on:
  push:
    branches:
      - master
    tags:
      - kvsearch-.*
      - codemirror-.*
  pull_request:
  merge_group:

jobs:
  benchmark:
    name: benchmark
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup npm environment
        uses: ./.github/actions/setup
      - run: npm install
      - run: cd kvsearch && npm run benchmark

  build-and-test:
    name: "build-and-test"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup npm environment
        uses: ./.github/actions/setup
      - run: npm install
      - run: npm run build
      - run: npm run build:cjs
      - run: npm test

  lint-lib:
    name: "lint-lib"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup npm environment
        uses: ./.github/actions/setup
      - run: npm install
      - run: npm run lint